# Auto-generated from SPDX license-list-data
# Do not edit manually

module Spdx
  # :nodoc:
  LICENSE_DATA = [
    {id: "0BSD", name: "BSD Zero Clause License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "3D-Slicer-1.0", name: "3D Slicer License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AAL", name: "Attribution Assurance License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Abstyles", name: "Abstyles License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AdaCore-doc", name: "AdaCore Doc License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Adobe-2006", name: "Adobe Systems Incorporated Source Code License Agreement", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Adobe-Display-PostScript", name: "Adobe Display PostScript License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Adobe-Glyph", name: "Adobe Glyph List License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Adobe-Utopia", name: "Adobe Utopia Font License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ADSL", name: "Amazon Digital Services License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Advanced-Cryptics-Dictionary", name: "Advanced Cryptics Dictionary License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AFL-1.1", name: "Academic Free License v1.1", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "AFL-1.2", name: "Academic Free License v1.2", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "AFL-2.0", name: "Academic Free License v2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "AFL-2.1", name: "Academic Free License v2.1", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "AFL-3.0", name: "Academic Free License v3.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Afmparse", name: "Afmparse License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AGPL-1.0", name: "Affero General Public License v1.0", osi_approved: false, fsf_libre: true, deprecated: true},
    {id: "AGPL-1.0-only", name: "Affero General Public License v1.0 only", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AGPL-1.0-or-later", name: "Affero General Public License v1.0 or later", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AGPL-3.0", name: "GNU Affero General Public License v3.0", osi_approved: true, fsf_libre: true, deprecated: true},
    {id: "AGPL-3.0-only", name: "GNU Affero General Public License v3.0 only", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "AGPL-3.0-or-later", name: "GNU Affero General Public License v3.0 or later", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Aladdin", name: "Aladdin Free Public License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ALGLIB-Documentation", name: "ALGLIB Documentation License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "AMD-newlib", name: "AMD newlib License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AMDPLPA", name: "AMD's plpa_map.c License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AML", name: "Apple MIT License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AML-glslang", name: "AML glslang variant License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "AMPAS", name: "Academy of Motion Picture Arts and Sciences BSD", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ANTLR-PD", name: "ANTLR Software Rights Notice", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ANTLR-PD-fallback", name: "ANTLR Software Rights Notice with license fallback", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "any-OSI", name: "Any OSI License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "any-OSI-perl-modules", name: "Any OSI License - Perl Modules", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Apache-1.0", name: "Apache License 1.0", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Apache-1.1", name: "Apache License 1.1", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Apache-2.0", name: "Apache License 2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "APAFML", name: "Adobe Postscript AFM License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "APL-1.0", name: "Adaptive Public License 1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "App-s2p", name: "App::s2p License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "APSL-1.0", name: "Apple Public Source License 1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "APSL-1.1", name: "Apple Public Source License 1.1", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "APSL-1.2", name: "Apple Public Source License 1.2", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "APSL-2.0", name: "Apple Public Source License 2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Arphic-1999", name: "Arphic Public License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Artistic-1.0", name: "Artistic License 1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Artistic-1.0-cl8", name: "Artistic License 1.0 w/clause 8", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Artistic-1.0-Perl", name: "Artistic License 1.0 (Perl)", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Artistic-2.0", name: "Artistic License 2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Artistic-dist", name: "Artistic License 1.0 (dist)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Aspell-RU", name: "Aspell Russian License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ASWF-Digital-Assets-1.0", name: "ASWF Digital Assets License version 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ASWF-Digital-Assets-1.1", name: "ASWF Digital Assets License 1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Baekmuk", name: "Baekmuk License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Bahyph", name: "Bahyph License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Barr", name: "Barr License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "bcrypt-Solar-Designer", name: "bcrypt Solar Designer License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Beerware", name: "Beerware License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Bitstream-Charter", name: "Bitstream Charter Font License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Bitstream-Vera", name: "Bitstream Vera Font License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BitTorrent-1.0", name: "BitTorrent Open Source License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BitTorrent-1.1", name: "BitTorrent Open Source License v1.1", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "blessing", name: "SQLite Blessing", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BlueOak-1.0.0", name: "Blue Oak Model License 1.0.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Boehm-GC", name: "Boehm-Demers-Weiser GC License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Boehm-GC-without-fee", name: "Boehm-Demers-Weiser GC License (without fee)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BOLA-1.1", name: "Buena Onda License Agreement v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Borceux", name: "Borceux license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Brian-Gladman-2-Clause", name: "Brian Gladman 2-Clause License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Brian-Gladman-3-Clause", name: "Brian Gladman 3-Clause License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-1-Clause", name: "BSD 1-Clause License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "BSD-2-Clause", name: "BSD 2-Clause \"Simplified\" License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "BSD-2-Clause-Darwin", name: "BSD 2-Clause - Ian Darwin variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-2-Clause-first-lines", name: "BSD 2-Clause - first lines requirement", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-2-Clause-FreeBSD", name: "BSD 2-Clause FreeBSD License", osi_approved: false, fsf_libre: true, deprecated: true},
    {id: "BSD-2-Clause-NetBSD", name: "BSD 2-Clause NetBSD License", osi_approved: false, fsf_libre: true, deprecated: true},
    {id: "BSD-2-Clause-Patent", name: "BSD-2-Clause Plus Patent License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "BSD-2-Clause-pkgconf-disclaimer", name: "BSD 2-Clause pkgconf disclaimer variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-2-Clause-Views", name: "BSD 2-Clause with views sentence", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause", name: "BSD 3-Clause \"New\" or \"Revised\" License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "BSD-3-Clause-acpica", name: "BSD 3-Clause acpica variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-Attribution", name: "BSD with attribution", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-Clear", name: "BSD 3-Clause Clear License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "BSD-3-Clause-flex", name: "BSD 3-Clause Flex variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-HP", name: "Hewlett-Packard BSD variant license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-LBNL", name: "Lawrence Berkeley National Labs BSD variant license", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-Modification", name: "BSD 3-Clause Modification", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-No-Military-License", name: "BSD 3-Clause No Military License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-No-Nuclear-License", name: "BSD 3-Clause No Nuclear License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-No-Nuclear-License-2014", name: "BSD 3-Clause No Nuclear License 2014", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-No-Nuclear-Warranty", name: "BSD 3-Clause No Nuclear Warranty", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-Open-MPI", name: "BSD 3-Clause Open MPI variant", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-Sun", name: "BSD 3-Clause Sun Microsystems", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-3-Clause-Tso", name: "BSD 3-Clause Tso variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-4-Clause", name: "BSD 4-Clause \"Original\" or \"Old\" License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "BSD-4-Clause-Shortened", name: "BSD 4 Clause Shortened", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-4-Clause-UC", name: "BSD-4-Clause (University of California-Specific)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-4.3RENO", name: "BSD 4.3 RENO License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-4.3TAHOE", name: "BSD 4.3 TAHOE License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-Advertising-Acknowledgement", name: "BSD Advertising Acknowledgement License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-Attribution-HPND-disclaimer", name: "BSD with Attribution and HPND disclaimer", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-Inferno-Nettverk", name: "BSD-Inferno-Nettverk", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-Mark-Modifications", name: "BSD Mark Modifications License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-Protection", name: "BSD Protection License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-Source-beginning-file", name: "BSD Source Code Attribution - beginning of file variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-Source-Code", name: "BSD Source Code Attribution", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-Systemics", name: "Systemics BSD variant license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSD-Systemics-W3Works", name: "Systemics W3Works BSD variant license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BSL-1.0", name: "Boost Software License 1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Buddy", name: "Buddy License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "BUSL-1.1", name: "Business Source License 1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "bzip2-1.0.5", name: "bzip2 and libbzip2 License v1.0.5", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "bzip2-1.0.6", name: "bzip2 and libbzip2 License v1.0.6", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "C-UDA-1.0", name: "Computational Use of Data Agreement v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CAL-1.0", name: "Cryptographic Autonomy License 1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "CAL-1.0-Combined-Work-Exception", name: "Cryptographic Autonomy License 1.0 (Combined Work Exception)", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Caldera", name: "Caldera License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Caldera-no-preamble", name: "Caldera License (without preamble)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CAPEC-tou", name: "Common Attack    Pattern Enumeration and Classification License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Catharon", name: "Catharon License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CATOSL-1.1", name: "Computer Associates Trusted Open Source License 1.1", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "CC-BY-1.0", name: "Creative Commons Attribution 1.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-2.0", name: "Creative Commons Attribution 2.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-2.5", name: "Creative Commons Attribution 2.5 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-2.5-AU", name: "Creative Commons Attribution 2.5 Australia", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-3.0", name: "Creative Commons Attribution 3.0 Unported", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-3.0-AT", name: "Creative Commons Attribution 3.0 Austria", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-3.0-AU", name: "Creative Commons Attribution 3.0 Australia", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-3.0-DE", name: "Creative Commons Attribution 3.0 Germany", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-3.0-IGO", name: "Creative Commons Attribution 3.0 IGO", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-3.0-NL", name: "Creative Commons Attribution 3.0 Netherlands", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-3.0-US", name: "Creative Commons Attribution 3.0 United States", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-4.0", name: "Creative Commons Attribution 4.0 International", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "CC-BY-NC-1.0", name: "Creative Commons Attribution Non Commercial 1.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-2.0", name: "Creative Commons Attribution Non Commercial 2.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-2.5", name: "Creative Commons Attribution Non Commercial 2.5 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-3.0", name: "Creative Commons Attribution Non Commercial 3.0 Unported", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-3.0-DE", name: "Creative Commons Attribution Non Commercial 3.0 Germany", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-4.0", name: "Creative Commons Attribution Non Commercial 4.0 International", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-ND-1.0", name: "Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-ND-2.0", name: "Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-ND-2.5", name: "Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-ND-3.0", name: "Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-ND-3.0-DE", name: "Creative Commons Attribution Non Commercial No Derivatives 3.0 Germany", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-ND-3.0-IGO", name: "Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-ND-4.0", name: "Creative Commons Attribution Non Commercial No Derivatives 4.0 International", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-1.0", name: "Creative Commons Attribution Non Commercial Share Alike 1.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-2.0", name: "Creative Commons Attribution Non Commercial Share Alike 2.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-2.0-DE", name: "Creative Commons Attribution Non Commercial Share Alike 2.0 Germany", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-2.0-FR", name: "Creative Commons Attribution-NonCommercial-ShareAlike 2.0 France", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-2.0-UK", name: "Creative Commons Attribution Non Commercial Share Alike 2.0 England and Wales", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-2.5", name: "Creative Commons Attribution Non Commercial Share Alike 2.5 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-3.0", name: "Creative Commons Attribution Non Commercial Share Alike 3.0 Unported", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-3.0-DE", name: "Creative Commons Attribution Non Commercial Share Alike 3.0 Germany", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-3.0-IGO", name: "Creative Commons Attribution Non Commercial Share Alike 3.0 IGO", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-NC-SA-4.0", name: "Creative Commons Attribution Non Commercial Share Alike 4.0 International", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-ND-1.0", name: "Creative Commons Attribution No Derivatives 1.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-ND-2.0", name: "Creative Commons Attribution No Derivatives 2.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-ND-2.5", name: "Creative Commons Attribution No Derivatives 2.5 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-ND-3.0", name: "Creative Commons Attribution No Derivatives 3.0 Unported", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-ND-3.0-DE", name: "Creative Commons Attribution No Derivatives 3.0 Germany", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-ND-4.0", name: "Creative Commons Attribution No Derivatives 4.0 International", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-1.0", name: "Creative Commons Attribution Share Alike 1.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-2.0", name: "Creative Commons Attribution Share Alike 2.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-2.0-UK", name: "Creative Commons Attribution Share Alike 2.0 England and Wales", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-2.1-JP", name: "Creative Commons Attribution Share Alike 2.1 Japan", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-2.5", name: "Creative Commons Attribution Share Alike 2.5 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-3.0", name: "Creative Commons Attribution Share Alike 3.0 Unported", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-3.0-AT", name: "Creative Commons Attribution Share Alike 3.0 Austria", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-3.0-DE", name: "Creative Commons Attribution Share Alike 3.0 Germany", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-3.0-IGO", name: "Creative Commons Attribution-ShareAlike 3.0 IGO", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-BY-SA-4.0", name: "Creative Commons Attribution Share Alike 4.0 International", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "CC-PDDC", name: "Creative Commons Public Domain Dedication and Certification", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-PDM-1.0", name: "Creative    Commons Public Domain Mark 1.0 Universal", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC-SA-1.0", name: "Creative Commons Share Alike 1.0 Generic", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CC0-1.0", name: "Creative Commons Zero v1.0 Universal", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "CDDL-1.0", name: "Common Development and Distribution License 1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "CDDL-1.1", name: "Common Development and Distribution License 1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CDL-1.0", name: "Common Documentation License 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CDLA-Permissive-1.0", name: "Community Data License Agreement Permissive 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CDLA-Permissive-2.0", name: "Community Data License Agreement Permissive 2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CDLA-Sharing-1.0", name: "Community Data License Agreement Sharing 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CECILL-1.0", name: "CeCILL Free Software License Agreement v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CECILL-1.1", name: "CeCILL Free Software License Agreement v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CECILL-2.0", name: "CeCILL Free Software License Agreement v2.0", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "CECILL-2.1", name: "CeCILL Free Software License Agreement v2.1", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "CECILL-B", name: "CeCILL-B Free Software License Agreement", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "CECILL-C", name: "CeCILL-C Free Software License Agreement", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "CERN-OHL-1.1", name: "CERN Open Hardware Licence v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CERN-OHL-1.2", name: "CERN Open Hardware Licence v1.2", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CERN-OHL-P-2.0", name: "CERN Open Hardware Licence Version 2 - Permissive", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "CERN-OHL-S-2.0", name: "CERN Open Hardware Licence Version 2 - Strongly Reciprocal", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "CERN-OHL-W-2.0", name: "CERN Open Hardware Licence Version 2 - Weakly Reciprocal", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "CFITSIO", name: "CFITSIO License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "check-cvs", name: "check-cvs License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "checkmk", name: "Checkmk License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ClArtistic", name: "Clarified Artistic License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Clips", name: "Clips License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CMU-Mach", name: "CMU Mach License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CMU-Mach-nodoc", name: "CMU    Mach - no notices-in-documentation variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CNRI-Jython", name: "CNRI Jython License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CNRI-Python", name: "CNRI Python License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "CNRI-Python-GPL-Compatible", name: "CNRI Python Open Source GPL Compatible License Agreement", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "COIL-1.0", name: "Copyfree Open Innovation License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Community-Spec-1.0", name: "Community Specification License 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Condor-1.1", name: "Condor Public License v1.1", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "copyleft-next-0.3.0", name: "copyleft-next 0.3.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "copyleft-next-0.3.1", name: "copyleft-next 0.3.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Cornell-Lossless-JPEG", name: "Cornell Lossless JPEG License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CPAL-1.0", name: "Common Public Attribution License 1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "CPL-1.0", name: "Common Public License 1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "CPOL-1.02", name: "Code Project Open License 1.02", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Cronyx", name: "Cronyx License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Crossword", name: "Crossword License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CryptoSwift", name: "CryptoSwift License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CrystalStacker", name: "CrystalStacker License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "CUA-OPL-1.0", name: "CUA Office Public License v1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Cube", name: "Cube License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "curl", name: "curl License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "cve-tou", name: "Common Vulnerability Enumeration ToU License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "D-FSL-1.0", name: "Deutsche Freie Software Lizenz", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DEC-3-Clause", name: "DEC 3-Clause License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "diffmark", name: "diffmark license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DL-DE-BY-2.0", name: "Data licence Germany – attribution – version 2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DL-DE-ZERO-2.0", name: "Data licence Germany – zero – version 2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DOC", name: "DOC License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DocBook-DTD", name: "DocBook DTD License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DocBook-Schema", name: "DocBook Schema License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DocBook-Stylesheet", name: "DocBook Stylesheet License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DocBook-XML", name: "DocBook XML License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Dotseqn", name: "Dotseqn License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DRL-1.0", name: "Detection Rule License 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DRL-1.1", name: "Detection Rule License 1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "DSDP", name: "DSDP License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "dtoa", name: "David M. Gay dtoa License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "dvipdfm", name: "dvipdfm License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ECL-1.0", name: "Educational Community License v1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "ECL-2.0", name: "Educational Community License v2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "eCos-2.0", name: "eCos license version 2.0", osi_approved: false, fsf_libre: true, deprecated: true},
    {id: "EFL-1.0", name: "Eiffel Forum License v1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "EFL-2.0", name: "Eiffel Forum License v2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "eGenix", name: "eGenix.com Public License 1.1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Elastic-2.0", name: "Elastic License 2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Entessa", name: "Entessa Public License v1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "EPICS", name: "EPICS Open License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "EPL-1.0", name: "Eclipse Public License 1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "EPL-2.0", name: "Eclipse Public License 2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "ErlPL-1.1", name: "Erlang Public License v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ESA-PL-permissive-2.4", name: "European Space Agency Public License – v2.4 – Permissive (Type 3)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ESA-PL-strong-copyleft-2.4", name: "European Space Agency Public License (ESA-PL) - V2.4 - Strong Copyleft (Type 1)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ESA-PL-weak-copyleft-2.4", name: "European Space Agency Public License – v2.4 – Weak Copyleft (Type 2)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "etalab-2.0", name: "Etalab Open License 2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "EUDatagrid", name: "EU DataGrid Software License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "EUPL-1.0", name: "European Union Public License 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "EUPL-1.1", name: "European Union Public License 1.1", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "EUPL-1.2", name: "European Union Public License 1.2", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Eurosym", name: "Eurosym License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Fair", name: "Fair License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "FBM", name: "Fuzzy Bitmap License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FDK-AAC", name: "Fraunhofer FDK AAC Codec Library", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Ferguson-Twofish", name: "Ferguson Twofish License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Frameworx-1.0", name: "Frameworx Open License 1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "FreeBSD-DOC", name: "FreeBSD Documentation License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FreeImage", name: "FreeImage Public License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FSFAP", name: "FSF All Permissive License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "FSFAP-no-warranty-disclaimer", name: "FSF All Permissive License (without Warranty)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FSFUL", name: "FSF Unlimited License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FSFULLR", name: "FSF Unlimited License (with License Retention)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FSFULLRSD", name: "FSF Unlimited License (with License Retention and Short Disclaimer)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FSFULLRWD", name: "FSF Unlimited License (With License Retention and Warranty Disclaimer)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FSL-1.1-ALv2", name: "Functional Source License, Version 1.1, ALv2 Future License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FSL-1.1-MIT", name: "Functional Source License, Version 1.1, MIT Future License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "FTL", name: "Freetype Project License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Furuseth", name: "Furuseth License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "fwlw", name: "fwlw License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Game-Programming-Gems", name: "Game Programming Gems License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GCR-docs", name: "Gnome GCR Documentation License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GD", name: "GD License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "generic-xts", name: "Generic XTS License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.1", name: "GNU Free Documentation License v1.1", osi_approved: false, fsf_libre: true, deprecated: true},
    {id: "GFDL-1.1-invariants-only", name: "GNU Free Documentation License v1.1 only - invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.1-invariants-or-later", name: "GNU Free Documentation License v1.1 or later - invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.1-no-invariants-only", name: "GNU Free Documentation License v1.1 only - no invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.1-no-invariants-or-later", name: "GNU Free Documentation License v1.1 or later - no invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.1-only", name: "GNU Free Documentation License v1.1 only", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "GFDL-1.1-or-later", name: "GNU Free Documentation License v1.1 or later", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "GFDL-1.2", name: "GNU Free Documentation License v1.2", osi_approved: false, fsf_libre: true, deprecated: true},
    {id: "GFDL-1.2-invariants-only", name: "GNU Free Documentation License v1.2 only - invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.2-invariants-or-later", name: "GNU Free Documentation License v1.2 or later - invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.2-no-invariants-only", name: "GNU Free Documentation License v1.2 only - no invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.2-no-invariants-or-later", name: "GNU Free Documentation License v1.2 or later - no invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.2-only", name: "GNU Free Documentation License v1.2 only", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "GFDL-1.2-or-later", name: "GNU Free Documentation License v1.2 or later", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "GFDL-1.3", name: "GNU Free Documentation License v1.3", osi_approved: false, fsf_libre: true, deprecated: true},
    {id: "GFDL-1.3-invariants-only", name: "GNU Free Documentation License v1.3 only - invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.3-invariants-or-later", name: "GNU Free Documentation License v1.3 or later - invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.3-no-invariants-only", name: "GNU Free Documentation License v1.3 only - no invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.3-no-invariants-or-later", name: "GNU Free Documentation License v1.3 or later - no invariants", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GFDL-1.3-only", name: "GNU Free Documentation License v1.3 only", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "GFDL-1.3-or-later", name: "GNU Free Documentation License v1.3 or later", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Giftware", name: "Giftware License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GL2PS", name: "GL2PS License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Glide", name: "3dfx Glide License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Glulxe", name: "Glulxe License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GLWTPL", name: "Good Luck With That Public License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "gnuplot", name: "gnuplot License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "GPL-1.0", name: "GNU General Public License v1.0 only", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "GPL-1.0+", name: "GNU General Public License v1.0 or later", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "GPL-1.0-only", name: "GNU General Public License v1.0 only", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GPL-1.0-or-later", name: "GNU General Public License v1.0 or later", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "GPL-2.0", name: "GNU General Public License v2.0 only", osi_approved: true, fsf_libre: true, deprecated: true},
    {id: "GPL-2.0+", name: "GNU General Public License v2.0 or later", osi_approved: true, fsf_libre: true, deprecated: true},
    {id: "GPL-2.0-only", name: "GNU General Public License v2.0 only", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "GPL-2.0-or-later", name: "GNU General Public License v2.0 or later", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "GPL-2.0-with-autoconf-exception", name: "GNU General Public License v2.0 w/Autoconf exception", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "GPL-2.0-with-bison-exception", name: "GNU General Public License v2.0 w/Bison exception", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "GPL-2.0-with-classpath-exception", name: "GNU General Public License v2.0 w/Classpath exception", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "GPL-2.0-with-font-exception", name: "GNU General Public License v2.0 w/Font exception", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "GPL-2.0-with-GCC-exception", name: "GNU General Public License v2.0 w/GCC Runtime Library exception", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "GPL-3.0", name: "GNU General Public License v3.0 only", osi_approved: true, fsf_libre: true, deprecated: true},
    {id: "GPL-3.0+", name: "GNU General Public License v3.0 or later", osi_approved: true, fsf_libre: true, deprecated: true},
    {id: "GPL-3.0-only", name: "GNU General Public License v3.0 only", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "GPL-3.0-or-later", name: "GNU General Public License v3.0 or later", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "GPL-3.0-with-autoconf-exception", name: "GNU General Public License v3.0 w/Autoconf exception", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "GPL-3.0-with-GCC-exception", name: "GNU General Public License v3.0 w/GCC Runtime Library exception", osi_approved: true, fsf_libre: false, deprecated: true},
    {id: "Graphics-Gems", name: "Graphics Gems License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "gSOAP-1.3b", name: "gSOAP Public License v1.3b", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "gtkbook", name: "gtkbook License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Gutmann", name: "Gutmann License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HaskellReport", name: "Haskell Language Report License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HDF5", name: "HDF5 License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "hdparm", name: "hdparm License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HIDAPI", name: "HIDAPI License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Hippocratic-2.1", name: "Hippocratic License 2.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HP-1986", name: "Hewlett-Packard 1986 License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HP-1989", name: "Hewlett-Packard 1989 License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND", name: "Historical Permission Notice and Disclaimer", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "HPND-DEC", name: "Historical Permission Notice and Disclaimer - DEC variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-doc", name: "Historical Permission Notice and Disclaimer - documentation variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-doc-sell", name: "Historical Permission Notice and Disclaimer - documentation sell variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-export-US", name: "HPND with US Government export control warning", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-export-US-acknowledgement", name: "HPND with US Government export control warning and acknowledgment", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-export-US-modify", name: "HPND with US Government export control warning and modification rqmt", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-export2-US", name: "HPND with US Government export control and 2 disclaimers", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-Fenneberg-Livingston", name: "Historical Permission Notice and Disclaimer - Fenneberg-Livingston variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-INRIA-IMAG", name: "Historical Permission Notice and Disclaimer    - INRIA-IMAG variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-Intel", name: "Historical Permission Notice and Disclaimer - Intel variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-Kevlin-Henney", name: "Historical Permission Notice and Disclaimer - Kevlin Henney variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-Markus-Kuhn", name: "Historical Permission Notice and Disclaimer - Markus Kuhn variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-merchantability-variant", name: "Historical Permission Notice and Disclaimer - merchantability variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-MIT-disclaimer", name: "Historical Permission Notice and Disclaimer with MIT disclaimer", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-Netrek", name: "Historical Permission Notice and Disclaimer - Netrek variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-Pbmplus", name: "Historical Permission Notice and Disclaimer - Pbmplus variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-sell-MIT-disclaimer-xserver", name: "Historical Permission Notice and Disclaimer - sell xserver variant with MIT disclaimer", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-sell-regexpr", name: "Historical Permission Notice and Disclaimer - sell regexpr variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-sell-variant", name: "Historical Permission Notice and Disclaimer - sell variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-sell-variant-critical-systems", name: "HPND - sell variant with safety critical systems clause", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-sell-variant-MIT-disclaimer", name: "HPND sell variant with MIT disclaimer", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-sell-variant-MIT-disclaimer-rev", name: "HPND sell variant with MIT disclaimer - reverse", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-SMC", name: "Historical Permission Notice and Disclaimer - SMC variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-UC", name: "Historical Permission Notice and Disclaimer - University of California variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HPND-UC-export-US", name: "Historical Permission Notice and Disclaimer - University of California, US export warning", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "HTMLTIDY", name: "HTML Tidy License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "hyphen-bulgarian", name: "hyphen-bulgarian License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "IBM-pibs", name: "IBM PowerPC Initialization and Boot Software", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ICU", name: "ICU License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "IEC-Code-Components-EULA", name: "IEC    Code Components End-user licence agreement", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "IJG", name: "Independent JPEG Group License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "IJG-short", name: "Independent JPEG Group License - short", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ImageMagick", name: "ImageMagick License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "iMatix", name: "iMatix Standard Function Library Agreement", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Imlib2", name: "Imlib2 License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Info-ZIP", name: "Info-ZIP License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Inner-Net-2.0", name: "Inner Net License v2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "InnoSetup", name: "Inno Setup License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Intel", name: "Intel Open Source License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Intel-ACPI", name: "Intel ACPI Software License Agreement", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Interbase-1.0", name: "Interbase Public License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "IPA", name: "IPA Font License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "IPL-1.0", name: "IBM Public License v1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "ISC", name: "ISC License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "ISC-Veillard", name: "ISC Veillard variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ISO-permission", name: "ISO permission notice", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Jam", name: "Jam License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "JasPer-2.0", name: "JasPer License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "jove", name: "Jove License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "JPL-image", name: "JPL Image Use Policy", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "JPNIC", name: "Japan Network Information Center License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "JSON", name: "JSON License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Kastrup", name: "Kastrup License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Kazlib", name: "Kazlib License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Knuth-CTAN", name: "Knuth CTAN License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LAL-1.2", name: "Licence Art Libre 1.2", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LAL-1.3", name: "Licence Art Libre 1.3", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Latex2e", name: "Latex2e License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Latex2e-translated-notice", name: "Latex2e with translated notice permission", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Leptonica", name: "Leptonica License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LGPL-2.0", name: "GNU Library General Public License v2 only", osi_approved: true, fsf_libre: false, deprecated: true},
    {id: "LGPL-2.0+", name: "GNU Library General Public License v2 or later", osi_approved: true, fsf_libre: false, deprecated: true},
    {id: "LGPL-2.0-only", name: "GNU Library General Public License v2 only", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "LGPL-2.0-or-later", name: "GNU Library General Public License v2 or later", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "LGPL-2.1", name: "GNU Lesser General Public License v2.1 only", osi_approved: true, fsf_libre: true, deprecated: true},
    {id: "LGPL-2.1+", name: "GNU Lesser General Public License v2.1 or later", osi_approved: true, fsf_libre: true, deprecated: true},
    {id: "LGPL-2.1-only", name: "GNU Lesser General Public License v2.1 only", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "LGPL-2.1-or-later", name: "GNU Lesser General Public License v2.1 or later", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "LGPL-3.0", name: "GNU Lesser General Public License v3.0 only", osi_approved: true, fsf_libre: true, deprecated: true},
    {id: "LGPL-3.0+", name: "GNU Lesser General Public License v3.0 or later", osi_approved: true, fsf_libre: true, deprecated: true},
    {id: "LGPL-3.0-only", name: "GNU Lesser General Public License v3.0 only", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "LGPL-3.0-or-later", name: "GNU Lesser General Public License v3.0 or later", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "LGPLLR", name: "Lesser General Public License For Linguistic Resources", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Libpng", name: "libpng License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "libpng-1.6.35", name: "PNG Reference Library License v1 (for libpng 0.5 through 1.6.35)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "libpng-2.0", name: "PNG Reference Library version 2", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "libselinux-1.0", name: "libselinux public domain notice", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "libtiff", name: "libtiff License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "libutil-David-Nugent", name: "libutil David Nugent License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LiLiQ-P-1.1", name: "Licence Libre du Québec – Permissive version 1.1", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "LiLiQ-R-1.1", name: "Licence Libre du Québec – Réciprocité version 1.1", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "LiLiQ-Rplus-1.1", name: "Licence Libre du Québec – Réciprocité forte version 1.1", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Linux-man-pages-1-para", name: "Linux man-pages - 1 paragraph", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Linux-man-pages-copyleft", name: "Linux man-pages Copyleft", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Linux-man-pages-copyleft-2-para", name: "Linux man-pages Copyleft - 2 paragraphs", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Linux-man-pages-copyleft-var", name: "Linux man-pages Copyleft Variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Linux-OpenIB", name: "Linux Kernel Variant of OpenIB.org license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LOOP", name: "Common Lisp LOOP License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LPD-document", name: "LPD Documentation License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LPL-1.0", name: "Lucent Public License Version 1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "LPL-1.02", name: "Lucent Public License v1.02", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "LPPL-1.0", name: "LaTeX Project Public License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LPPL-1.1", name: "LaTeX Project Public License v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LPPL-1.2", name: "LaTeX Project Public License v1.2", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "LPPL-1.3a", name: "LaTeX Project Public License v1.3a", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "LPPL-1.3c", name: "LaTeX Project Public License v1.3c", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "lsof", name: "lsof License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Lucida-Bitmap-Fonts", name: "Lucida Bitmap Fonts License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LZMA-SDK-9.11-to-9.20", name: "LZMA SDK License (versions 9.11 to 9.20)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "LZMA-SDK-9.22", name: "LZMA SDK License (versions 9.22 and beyond)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Mackerras-3-Clause", name: "Mackerras 3-Clause License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Mackerras-3-Clause-acknowledgment", name: "Mackerras 3-Clause - acknowledgment variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "magaz", name: "magaz License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "mailprio", name: "mailprio License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MakeIndex", name: "MakeIndex License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "man2html", name: "man2html License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Martin-Birgmeier", name: "Martin Birgmeier License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "McPhee-slideshow", name: "McPhee Slideshow License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "metamail", name: "metamail License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Minpack", name: "Minpack License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIPS", name: "MIPS License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MirOS", name: "The MirOS Licence", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "MIT", name: "MIT License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "MIT-0", name: "MIT No Attribution", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "MIT-advertising", name: "Enlightenment License (e16)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-Click", name: "MIT Click License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-CMU", name: "CMU License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-enna", name: "enna License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-feh", name: "feh License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-Festival", name: "MIT Festival Variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-Khronos-old", name: "MIT Khronos - old variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-Modern-Variant", name: "MIT License Modern Variant", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "MIT-open-group", name: "MIT Open Group variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-STK", name: "MIT-STK License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-testregex", name: "MIT testregex Variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MIT-Wu", name: "MIT Tom Wu Variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MITNFA", name: "MIT +no-false-attribs license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MMIXware", name: "MMIXware License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MMPL-1.0.1", name: "Minecraft Mod Public License v1.0.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Motosoto", name: "Motosoto License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "MPEG-SSG", name: "MPEG Software Simulation", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "mpi-permissive", name: "mpi Permissive License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "mpich2", name: "mpich2 License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MPL-1.0", name: "Mozilla Public License 1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "MPL-1.1", name: "Mozilla Public License 1.1", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "MPL-2.0", name: "Mozilla Public License 2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "MPL-2.0-no-copyleft-exception", name: "Mozilla Public License 2.0 (no copyleft exception)", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "mplus", name: "mplus Font License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MS-LPL", name: "Microsoft Limited Public License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MS-PL", name: "Microsoft Public License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "MS-RL", name: "Microsoft Reciprocal License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "MTLL", name: "Matrix Template Library License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MulanPSL-1.0", name: "Mulan Permissive Software License, Version 1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "MulanPSL-2.0", name: "Mulan Permissive Software License, Version 2", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Multics", name: "Multics License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Mup", name: "Mup License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NAIST-2003", name: "Nara Institute of Science and Technology License (2003)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NASA-1.3", name: "NASA Open Source Agreement 1.3", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Naumen", name: "Naumen Public License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "NBPL-1.0", name: "Net Boolean Public License v1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NCBI-PD", name: "NCBI Public Domain Notice", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NCGL-UK-2.0", name: "Non-Commercial Government Licence", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NCL", name: "NCL Source Code License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NCSA", name: "University of Illinois/NCSA Open Source License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Net-SNMP", name: "Net-SNMP License", osi_approved: false, fsf_libre: false, deprecated: true},
    {id: "NetCDF", name: "NetCDF license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Newsletr", name: "Newsletr License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NGPL", name: "Nethack General Public License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "ngrep", name: "ngrep License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NICTA-1.0", name: "NICTA Public Software License, Version 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NIST-PD", name: "NIST Public Domain Notice", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NIST-PD-fallback", name: "NIST Public Domain Notice with license fallback", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NIST-PD-TNT", name: "NIST    Public Domain Notice TNT variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NIST-Software", name: "NIST Software License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NLOD-1.0", name: "Norwegian Licence for Open Government Data (NLOD) 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NLOD-2.0", name: "Norwegian Licence for Open Government Data (NLOD) 2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NLPL", name: "No Limit Public License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Nokia", name: "Nokia Open Source License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "NOSL", name: "Netizen Open Source License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Noweb", name: "Noweb License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NPL-1.0", name: "Netscape Public License v1.0", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "NPL-1.1", name: "Netscape Public License v1.1", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "NPOSL-3.0", name: "Non-Profit Open Software License 3.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "NRL", name: "NRL License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NTIA-PD", name: "NTIA Public Domain Notice", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "NTP", name: "NTP License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "NTP-0", name: "NTP No Attribution", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Nunit", name: "Nunit License", osi_approved: false, fsf_libre: true, deprecated: true},
    {id: "O-UDA-1.0", name: "Open Use of Data Agreement v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OAR", name: "OAR License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OCCT-PL", name: "Open CASCADE Technology Public License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OCLC-2.0", name: "OCLC Research Public License 2.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "ODbL-1.0", name: "Open Data Commons Open Database License v1.0", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "ODC-By-1.0", name: "Open Data Commons Attribution License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OFFIS", name: "OFFIS License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OFL-1.0", name: "SIL Open Font License 1.0", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "OFL-1.0-no-RFN", name: "SIL Open Font License 1.0 with no Reserved Font Name", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OFL-1.0-RFN", name: "SIL Open Font License 1.0 with Reserved Font Name", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OFL-1.1", name: "SIL Open Font License 1.1", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "OFL-1.1-no-RFN", name: "SIL Open Font License 1.1 with no Reserved Font Name", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "OFL-1.1-RFN", name: "SIL Open Font License 1.1 with Reserved Font Name", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "OGC-1.0", name: "OGC Software License, Version 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OGDL-Taiwan-1.0", name: "Taiwan Open Government Data License, version 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OGL-Canada-2.0", name: "Open Government Licence - Canada", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OGL-UK-1.0", name: "Open Government Licence v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OGL-UK-2.0", name: "Open Government Licence v2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OGL-UK-3.0", name: "Open Government Licence v3.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OGTSL", name: "Open Group Test Suite License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "OLDAP-1.1", name: "Open LDAP Public License v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-1.2", name: "Open LDAP Public License v1.2", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-1.3", name: "Open LDAP Public License v1.3", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-1.4", name: "Open LDAP Public License v1.4", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.0", name: "Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.0.1", name: "Open LDAP Public License v2.0.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.1", name: "Open LDAP Public License v2.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.2", name: "Open LDAP Public License v2.2", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.2.1", name: "Open LDAP Public License v2.2.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.2.2", name: "Open LDAP Public License 2.2.2", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.3", name: "Open LDAP Public License v2.3", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "OLDAP-2.4", name: "Open LDAP Public License v2.4", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.5", name: "Open LDAP Public License v2.5", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.6", name: "Open LDAP Public License v2.6", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OLDAP-2.7", name: "Open LDAP Public License v2.7", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "OLDAP-2.8", name: "Open LDAP Public License v2.8", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "OLFL-1.3", name: "Open Logistics Foundation License Version 1.3", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "OML", name: "Open Market License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OpenMDW-1.0", name: "OpenMDW License Agreement v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OpenPBS-2.3", name: "OpenPBS v2.3 Software License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OpenSSL", name: "OpenSSL License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "OpenSSL-standalone", name: "OpenSSL License - standalone", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OpenVision", name: "OpenVision License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OPL-1.0", name: "Open Public License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OPL-UK-3.0", name: "United    Kingdom Open Parliament Licence v3.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OPUBL-1.0", name: "Open Publication License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "OSC-1.0", name: "OSC License 1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "OSET-PL-2.1", name: "OSET Public License version 2.1", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "OSL-1.0", name: "Open Software License 1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "OSL-1.1", name: "Open Software License 1.1", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "OSL-2.0", name: "Open Software License 2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "OSL-2.1", name: "Open Software License 2.1", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "OSL-3.0", name: "Open Software License 3.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "OSSP", name: "OSSP License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "PADL", name: "PADL License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ParaType-Free-Font-1.3", name: "ParaType Free Font Licensing Agreement v1.3", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Parity-6.0.0", name: "The Parity Public License 6.0.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Parity-7.0.0", name: "The Parity Public License 7.0.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "PDDL-1.0", name: "Open Data Commons Public Domain Dedication & License 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "PHP-3.0", name: "PHP License v3.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "PHP-3.01", name: "PHP License v3.01", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Pixar", name: "Pixar License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "pkgconf", name: "pkgconf License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Plexus", name: "Plexus Classworlds License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "pnmstitch", name: "pnmstitch License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "PolyForm-Noncommercial-1.0.0", name: "PolyForm Noncommercial License 1.0.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "PolyForm-Small-Business-1.0.0", name: "PolyForm Small Business License 1.0.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "PostgreSQL", name: "PostgreSQL License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "PPL", name: "Peer Production License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "PSF-2.0", name: "Python Software Foundation License 2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "psfrag", name: "psfrag License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "psutils", name: "psutils License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Python-2.0", name: "Python License 2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Python-2.0.1", name: "Python License 2.0.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "python-ldap", name: "Python ldap License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Qhull", name: "Qhull License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "QPL-1.0", name: "Q Public License 1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "QPL-1.0-INRIA-2004", name: "Q Public License 1.0 - INRIA 2004 variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "radvd", name: "radvd License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Rdisc", name: "Rdisc License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "RHeCos-1.1", name: "Red Hat eCos Public License v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "RPL-1.1", name: "Reciprocal Public License 1.1", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "RPL-1.5", name: "Reciprocal Public License 1.5", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "RPSL-1.0", name: "RealNetworks Public Source License v1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "RSA-MD", name: "RSA Message-Digest License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "RSCPL", name: "Ricoh Source Code Public License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Ruby", name: "Ruby License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Ruby-pty", name: "Ruby pty extension license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SAX-PD", name: "Sax Public Domain Notice", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SAX-PD-2.0", name: "Sax Public Domain Notice 2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Saxpath", name: "Saxpath License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SCEA", name: "SCEA Shared Source License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SchemeReport", name: "Scheme Language Report License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Sendmail", name: "Sendmail License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Sendmail-8.23", name: "Sendmail License 8.23", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Sendmail-Open-Source-1.1", name: "Sendmail Open Source License v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SGI-B-1.0", name: "SGI Free Software License B v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SGI-B-1.1", name: "SGI Free Software License B v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SGI-B-2.0", name: "SGI Free Software License B v2.0", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "SGI-OpenGL", name: "SGI OpenGL License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SGMLUG-PM", name: "SGMLUG Parser Materials License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SGP4", name: "SGP4 Permission Notice", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SHL-0.5", name: "Solderpad Hardware License v0.5", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SHL-0.51", name: "Solderpad Hardware License, Version 0.51", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SimPL-2.0", name: "Simple Public License 2.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "SISSL", name: "Sun Industry Standards Source License v1.1", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "SISSL-1.2", name: "Sun Industry Standards Source License v1.2", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SL", name: "SL License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Sleepycat", name: "Sleepycat License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "SMAIL-GPL", name: "SMAIL General Public License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SMLNJ", name: "Standard ML of New Jersey License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "SMPPL", name: "Secure Messaging Protocol Public License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SNIA", name: "SNIA Public License 1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "snprintf", name: "snprintf License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SOFA", name: "SOFA Software License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "softSurfer", name: "softSurfer License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Soundex", name: "Soundex License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Spencer-86", name: "Spencer License 86", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Spencer-94", name: "Spencer License 94", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Spencer-99", name: "Spencer License 99", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SPL-1.0", name: "Sun Public License v1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "ssh-keyscan", name: "ssh-keyscan License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SSH-OpenSSH", name: "SSH OpenSSH license", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SSH-short", name: "SSH short notice", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SSLeay-standalone", name: "SSLeay License - standalone", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SSPL-1.0", name: "Server Side Public License, v 1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "StandardML-NJ", name: "Standard ML of New Jersey License", osi_approved: false, fsf_libre: true, deprecated: true},
    {id: "SugarCRM-1.1.3", name: "SugarCRM Public License v1.1.3", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SUL-1.0", name: "Sustainable Use License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Sun-PPP", name: "Sun PPP License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Sun-PPP-2000", name: "Sun PPP License (2000)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SunPro", name: "SunPro License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "SWL", name: "Scheme Widget Library (SWL) Software License Agreement", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "swrule", name: "swrule License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Symlinks", name: "Symlinks License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TAPR-OHL-1.0", name: "TAPR Open Hardware License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TCL", name: "TCL/TK License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TCP-wrappers", name: "TCP Wrappers License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TekHVC", name: "TekHVC License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TermReadKey", name: "TermReadKey License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TGPPL-1.0", name: "Transitive Grace Period Public Licence 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ThirdEye", name: "ThirdEye License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "threeparttable", name: "threeparttable License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TMate", name: "TMate Open Source License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TORQUE-1.1", name: "TORQUE v2.5+ Software License v1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TOSL", name: "Trusster Open Source License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TPDL", name: "Time::ParseDate License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TPL-1.0", name: "THOR Public License 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TrustedQSL", name: "TrustedQSL License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TTWL", name: "Text-Tabs+Wrap License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TTYP0", name: "TTYP0 License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TU-Berlin-1.0", name: "Technische Universitaet Berlin License 1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "TU-Berlin-2.0", name: "Technische Universitaet Berlin License 2.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Ubuntu-font-1.0", name: "Ubuntu Font Licence v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "UCAR", name: "UCAR License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "UCL-1.0", name: "Upstream Compatibility License v1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "ulem", name: "ulem License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "UMich-Merit", name: "Michigan/Merit Networks License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Unicode-3.0", name: "Unicode License v3", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Unicode-DFS-2015", name: "Unicode License Agreement - Data Files and Software (2015)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Unicode-DFS-2016", name: "Unicode License Agreement - Data Files and Software (2016)", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Unicode-TOU", name: "Unicode Terms of Use", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "UnixCrypt", name: "UnixCrypt License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Unlicense", name: "The Unlicense", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "Unlicense-libtelnet", name: "Unlicense - libtelnet variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Unlicense-libwhirlpool", name: "Unlicense - libwhirlpool variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "UnRAR", name: "UnRAR License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "UPL-1.0", name: "Universal Permissive License v1.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "URT-RLE", name: "Utah Raster Toolkit Run Length Encoded License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Vim", name: "Vim License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Vixie-Cron", name: "Vixie Cron License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "VOSTROM", name: "VOSTROM Public License for Open Source", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "VSL-1.0", name: "Vovida Software License v1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "W3C", name: "W3C Software Notice and License (2002-12-31)", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "W3C-19980720", name: "W3C Software Notice and License (1998-07-20)", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "W3C-20150513", name: "W3C Software Notice and Document License (2015-05-13)", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "w3m", name: "w3m License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Watcom-1.0", name: "Sybase Open Watcom Public License 1.0", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Widget-Workshop", name: "Widget Workshop License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "WordNet", name: "WordNet License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "Wsuipa", name: "Wsuipa License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "WTFNMFPL", name: "Do What The F*ck You Want To But It's Not My Fault Public License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "WTFPL", name: "Do What The F*ck You Want To Public License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "wwl", name: "WWL License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "wxWindows", name: "wxWindows Library License", osi_approved: true, fsf_libre: false, deprecated: true},
    {id: "X11", name: "X11 License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "X11-distribute-modifications-variant", name: "X11 License Distribution Modification Variant", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "X11-no-permit-persons", name: "X11 no permit persons clause", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "X11-swapped", name: "X11 swapped final paragraphs", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Xdebug-1.03", name: "Xdebug License v 1.03", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Xerox", name: "Xerox License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Xfig", name: "Xfig License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "XFree86-1.1", name: "XFree86 License 1.1", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "xinetd", name: "xinetd License", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "xkeyboard-config-Zinoviev", name: "xkeyboard-config Zinoviev License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "xlock", name: "xlock License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Xnet", name: "X.Net License", osi_approved: true, fsf_libre: false, deprecated: false},
    {id: "xpp", name: "XPP License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "XSkat", name: "XSkat License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "xzoom", name: "xzoom License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "YPL-1.0", name: "Yahoo! Public License v1.0", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "YPL-1.1", name: "Yahoo! Public License v1.1", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Zed", name: "Zed License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Zeeff", name: "Zeeff License", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Zend-2.0", name: "Zend License v2.0", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Zimbra-1.3", name: "Zimbra Public License v1.3", osi_approved: false, fsf_libre: true, deprecated: false},
    {id: "Zimbra-1.4", name: "Zimbra Public License v1.4", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "Zlib", name: "zlib License", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "zlib-acknowledgement", name: "zlib/libpng License with Acknowledgement", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ZPL-1.1", name: "Zope Public License 1.1", osi_approved: false, fsf_libre: false, deprecated: false},
    {id: "ZPL-2.0", name: "Zope Public License 2.0", osi_approved: true, fsf_libre: true, deprecated: false},
    {id: "ZPL-2.1", name: "Zope Public License 2.1", osi_approved: true, fsf_libre: true, deprecated: false},
  ]

  # :nodoc:
  EXCEPTION_DATA = [
    {id: "389-exception", name: "389 Directory Server Exception", deprecated: false},
    {id: "Asterisk-exception", name: "Asterisk exception", deprecated: false},
    {id: "Asterisk-linking-protocols-exception", name: "Asterisk linking protocols exception", deprecated: false},
    {id: "Autoconf-exception-2.0", name: "Autoconf exception 2.0", deprecated: false},
    {id: "Autoconf-exception-3.0", name: "Autoconf exception 3.0", deprecated: false},
    {id: "Autoconf-exception-generic", name: "Autoconf generic exception", deprecated: false},
    {id: "Autoconf-exception-generic-3.0", name: "Autoconf generic exception for GPL-3.0", deprecated: false},
    {id: "Autoconf-exception-macro", name: "Autoconf macro exception", deprecated: false},
    {id: "Bison-exception-1.24", name: "Bison exception 1.24", deprecated: false},
    {id: "Bison-exception-2.2", name: "Bison exception 2.2", deprecated: false},
    {id: "Bootloader-exception", name: "Bootloader Distribution Exception", deprecated: false},
    {id: "CGAL-linking-exception", name: "CGAL Linking Exception", deprecated: false},
    {id: "Classpath-exception-2.0", name: "Classpath exception 2.0", deprecated: false},
    {id: "Classpath-exception-2.0-short", name: "Classpath exception 2.0 - short", deprecated: false},
    {id: "CLISP-exception-2.0", name: "CLISP exception 2.0", deprecated: false},
    {id: "cryptsetup-OpenSSL-exception", name: "cryptsetup OpenSSL exception", deprecated: false},
    {id: "Digia-Qt-LGPL-exception-1.1", name: "Digia Qt LGPL Exception version 1.1", deprecated: false},
    {id: "DigiRule-FOSS-exception", name: "DigiRule FOSS License Exception", deprecated: false},
    {id: "eCos-exception-2.0", name: "eCos exception 2.0", deprecated: false},
    {id: "erlang-otp-linking-exception", name: "Erlang/OTP Linking Exception", deprecated: false},
    {id: "Fawkes-Runtime-exception", name: "Fawkes Runtime Exception", deprecated: false},
    {id: "FLTK-exception", name: "FLTK exception", deprecated: false},
    {id: "fmt-exception", name: "fmt exception", deprecated: false},
    {id: "Font-exception-2.0", name: "Font exception 2.0", deprecated: false},
    {id: "freertos-exception-2.0", name: "FreeRTOS Exception 2.0", deprecated: false},
    {id: "GCC-exception-2.0", name: "GCC Runtime Library exception 2.0", deprecated: false},
    {id: "GCC-exception-2.0-note", name: "GCC    Runtime Library exception 2.0 - note variant", deprecated: false},
    {id: "GCC-exception-3.1", name: "GCC Runtime Library exception 3.1", deprecated: false},
    {id: "Gmsh-exception", name: "Gmsh exception", deprecated: false},
    {id: "GNAT-exception", name: "GNAT exception", deprecated: false},
    {id: "GNOME-examples-exception", name: "GNOME examples exception", deprecated: false},
    {id: "GNU-compiler-exception", name: "GNU Compiler Exception", deprecated: false},
    {id: "gnu-javamail-exception", name: "GNU JavaMail exception", deprecated: false},
    {id: "GPL-3.0-389-ds-base-exception", name: "GPL-3.0 389 DS Base Exception", deprecated: false},
    {id: "GPL-3.0-interface-exception", name: "GPL-3.0 Interface Exception", deprecated: false},
    {id: "GPL-3.0-linking-exception", name: "GPL-3.0 Linking Exception", deprecated: false},
    {id: "GPL-3.0-linking-source-exception", name: "GPL-3.0 Linking Exception (with Corresponding Source)", deprecated: false},
    {id: "GPL-CC-1.0", name: "GPL Cooperation Commitment 1.0", deprecated: false},
    {id: "GStreamer-exception-2005", name: "GStreamer Exception (2005)", deprecated: false},
    {id: "GStreamer-exception-2008", name: "GStreamer Exception (2008)", deprecated: false},
    {id: "harbour-exception", name: "harbour exception", deprecated: false},
    {id: "i2p-gpl-java-exception", name: "i2p GPL+Java Exception", deprecated: false},
    {id: "Independent-modules-exception", name: "Independent Module Linking exception", deprecated: false},
    {id: "KiCad-libraries-exception", name: "KiCad Libraries Exception", deprecated: false},
    {id: "kvirc-openssl-exception", name: "kvirc OpenSSL Exception", deprecated: false},
    {id: "LGPL-3.0-linking-exception", name: "LGPL-3.0 Linking Exception", deprecated: false},
    {id: "libpri-OpenH323-exception", name: "libpri OpenH323 exception", deprecated: false},
    {id: "Libtool-exception", name: "Libtool Exception", deprecated: false},
    {id: "Linux-syscall-note", name: "Linux Syscall Note", deprecated: false},
    {id: "LLGPL", name: "LLGPL Preamble", deprecated: false},
    {id: "LLVM-exception", name: "LLVM Exception", deprecated: false},
    {id: "LZMA-exception", name: "LZMA exception", deprecated: false},
    {id: "mif-exception", name: "Macros and Inline Functions Exception", deprecated: false},
    {id: "mxml-exception", name: "mxml Exception", deprecated: false},
    {id: "Nokia-Qt-exception-1.1", name: "Nokia Qt LGPL exception 1.1", deprecated: true},
    {id: "OCaml-LGPL-linking-exception", name: "OCaml LGPL Linking Exception", deprecated: false},
    {id: "OCCT-exception-1.0", name: "Open CASCADE Exception 1.0", deprecated: false},
    {id: "OpenJDK-assembly-exception-1.0", name: "OpenJDK Assembly exception 1.0", deprecated: false},
    {id: "openvpn-openssl-exception", name: "OpenVPN OpenSSL Exception", deprecated: false},
    {id: "PCRE2-exception", name: "PCRE2 exception", deprecated: false},
    {id: "polyparse-exception", name: "Polyparse Exception", deprecated: false},
    {id: "PS-or-PDF-font-exception-20170817", name: "PS/PDF font exception (2017-08-17)", deprecated: false},
    {id: "QPL-1.0-INRIA-2004-exception", name: "INRIA QPL 1.0 2004 variant exception", deprecated: false},
    {id: "Qt-GPL-exception-1.0", name: "Qt GPL exception 1.0", deprecated: false},
    {id: "Qt-LGPL-exception-1.1", name: "Qt LGPL exception 1.1", deprecated: false},
    {id: "Qwt-exception-1.0", name: "Qwt exception 1.0", deprecated: false},
    {id: "romic-exception", name: "Romic Exception", deprecated: false},
    {id: "RRDtool-FLOSS-exception-2.0", name: "RRDtool FLOSS exception 2.0", deprecated: false},
    {id: "rsync-linking-exception", name: "rsync Linking Exception", deprecated: false},
    {id: "SANE-exception", name: "SANE Exception", deprecated: false},
    {id: "SHL-2.0", name: "Solderpad Hardware License v2.0", deprecated: false},
    {id: "SHL-2.1", name: "Solderpad Hardware License v2.1", deprecated: false},
    {id: "Simple-Library-Usage-exception", name: "Simple Library Usage Exception", deprecated: false},
    {id: "sqlitestudio-OpenSSL-exception", name: "sqlitestudio OpenSSL exception", deprecated: false},
    {id: "stunnel-exception", name: "stunnel Exception", deprecated: false},
    {id: "SWI-exception", name: "SWI exception", deprecated: false},
    {id: "Swift-exception", name: "Swift Exception", deprecated: false},
    {id: "Texinfo-exception", name: "Texinfo exception", deprecated: false},
    {id: "u-boot-exception-2.0", name: "U-Boot exception 2.0", deprecated: false},
    {id: "UBDL-exception", name: "Unmodified Binary Distribution exception", deprecated: false},
    {id: "Universal-FOSS-exception-1.0", name: "Universal FOSS Exception, Version 1.0", deprecated: false},
    {id: "vsftpd-openssl-exception", name: "vsftpd OpenSSL exception", deprecated: false},
    {id: "WxWindows-exception-3.1", name: "WxWindows Library Exception 3.1", deprecated: false},
    {id: "x11vnc-openssl-exception", name: "x11vnc OpenSSL Exception", deprecated: false},
  ]
end
